apiVersion: v1
kind: Service
metadata:
  name: app-mysql
  labels:
    app: app-mysql
spec:
  type: NodePort
  selector:
    app: app-mysql
  ports:
  - name: http
    port: 4000
    targetPort: 4000
